name: "Test"

on:
  pull_request:

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: Get information
        id: info
        uses: openpeerpower/actions/helpers/info@main

  build:
    name: Test action build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: Build the builder
        uses: openpeerpower/builder@main
        with:
          args: |
            --test \
            --amd64 \
            --target /data \
            --generic latest

      - name: Test ${{ matrix.architecture }} builder
        uses: ./
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target /data \
            --generic ${{ github.sha }}
